### ISSUE TITLE
undefined variable new_field

### ISSUE THREAD

**Issue by Loungagna** [CargoSense/ex_csv#11]
`mix test ` fails on lines 63, 74, 161, 181, 180 with `undefined variable new_field` reason is it should be written `new_field()`

**Comment by benwilson512** [comment]
Hi @Loungagna I think the plan here is to just retire this library at this point. There many better alternatives now,  and I see no need for us to update this library. I'd recommend https://hexdocs.pm/nimble_csv/NimbleCSV.html or https://hexdocs.pm/csv/readme.html
